routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'SearchController@search')->name('search');
Route::post('/status', 'StatusController@store')->name('status.store');
Route::post('/timeline-photo', 'TimelinePhotoController@store')->name('timeline-photo.store');
Route::get('/profile/{user}', 'ProfileController@show')->name('profile.show');

Route::post('user/{receiver}/friendship/add', 'FriendshipController@addFriend')->name('friendship.add');
Route::post('/friendship/{friendship}/accept', 'FriendshipController@acceptFriend')->name('friendship.accept');
Route::post('/friendship/{friendship}/refuse', 'FriendshipController@refuseFriend')->name('friendship.refuse');
Route::post('/friendship/{friendship}/remove', 'FriendshipController@removeFriend')->name('friendship.remove');
Route::get('/friends', 'ProfileController@friends')->name('friends');
Route::get('/settings', 'SettingsController@edit')->name('profile.settings');
Route::put('/settings', 'SettingsController@update')->name('profile.settings.update');

Route::post('/post/{post}/comments', 'CommentController@store')->name('post.comments.store');
Route::post('/post/{post}/likes', 'LikeController@like')->name('post.like');
Route::delete('/post/{post}/likes', 'LikeController@unlike')->name('post.unlike');

app/Models/TimelinePhoto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TimelinePhoto extends Model
{
    protected $fillable = ['description', 'name', 'post_id'];

    /*
     * Accessors and mutators
     */

    public function getDescriptionAttribute($description)
    {
        return nl2br($description);
    }

    public function getMediumPathAttribute()
    {
        if ($this->name) {
            return \Storage::disk('public')->url('/timeline-photos/medium/' . $this->name);
        }

        $randomImage = random_int(0, 600);
        return "https://picsum.photos/800/540/?image={$randomImage}";
    }
}

app/User.php
<?php

namespace App;

use App\Models\Friendship;
use App\Models\Post;
use App\Models\Role;
use DB;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Sofa\Eloquence\Eloquence;

class User extends Authenticatable
{
    use Notifiable, Eloquence;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'description', 'profile_photo'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $searchableColumns = ['name'];

    /*
     * Relationships
     */

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function all_friendships()
    {
        return Friendship::where('sender_id', $this->id)
            ->orWhere('receiver_id', $this->id);
    }

    public function friendships()
    {
        return Friendship::where('sender_id', $this->id)
            ->orWhere('receiver_id', $this->id)
            ->accepted()
            ->with(['sender', 'receiver']);
    }

    public function getFriendsIds()
    {
        $receiverIds = DB::table('friendships')
            ->where('sender_id', $this->id)
            ->whereNull('deleted_at')
            ->where('accepted', 1)
            ->pluck('receiver_id')
            ->toArray();

        $senderIds = DB::table('friendships')
            ->where('receiver_id', $this->id)
            ->whereNull('deleted_at')
            ->where('accepted', 1)
            ->pluck('sender_id')
            ->toArray();

        return array_unique(array_merge($receiverIds, $senderIds));
    }

    public function getMyFriendRequests()
    {
        return Friendship::where('receiver_id', $this->id)
            ->pending()
            ->with(['sender', 'receiver'])
            ->get();
    }

    public function getMyFriendRequestsCount()
    {
        return Friendship::where('receiver_id', $this->id)
            ->pending()
            ->with(['sender', 'receiver'])
            ->count();
    }

    /**
     * @return User
     */
    public function friends()
    {
        $receivers = DB::table('friendships')
            ->where('accepted', 1)
            ->where('sender_id', $this->id)
            ->whereNull('deleted_at')
            ->pluck('receiver_id')
            ->toArray();

        $senders = DB::table('friendships')
            ->where('accepted', 1)
            ->where('receiver_id', $this->id)
            ->whereNull('deleted_at')
            ->pluck('sender_id')
            ->toArray();

        $friendsIds = array_merge($receivers, $senders);

        return User::whereIn('id', $friendsIds)
            ->orderBy('name', 'ASC');
    }

    /*
     * Methods
     */

    /**
     * @param User $otherUser
     * @return Friendship|null
     */
    public function isFriendWith($otherUser)
    {
        return Friendship::accepted()
            ->connected(\Auth::user(), $otherUser)
            ->first();
    }

    /**
     * @param User $otherUser
     * @return Friendship|null
     */
    public function hasPendingFriendRequestWith($otherUser)
    {
        return Friendship::pending()
            ->connected(\Auth::user(), $otherUser)
            ->first();
    }

    /*
     * Accessors and mutators
     */

    public function getFriendshipsAttribute()
    {
        return $this->friendships()->get();
    }

    public function getProfilePhotoThumbnailPathAttribute()
    {
        if ($this->profile_photo) {
            return \Storage::disk('public')->url('/img/thumbnail/' . $this->profile_photo);
        }

        return "https://api.adorable.io/avatars/100/{$this->email}";
    }

    public function getProfilePhotoMediumPathAttribute()
    {
        if ($this->profile_photo) {
            return \Storage::disk('public')->url('/img/medium/' . $this->profile_photo);
        }

        return "https://api.adorable.io/avatars/200/{$this->email}";
    }
}

resources/views/partials/new-post.blade.php
<div class="card mb-3">
  <div class="card-header">Post new photo</div>

  <div class="card-body">
    {{ Form::open(['route' => 'timeline-photo.store', 'method' => 'POST', 'files' => true ]) }}
    <div class="form-group">
      <label for="timeline_photo">Pick a photo</label>
      {{ Form::file('timeline_photo', ['class' => 'form-control-file', 'required', 'id' => 'timeline_photo']) }}
    </div>

    <div class="form-group">
      <textarea name="description" id="description" rows="3" class="form-control"
                placeholder="What's on your photo"></textarea>
    </div>

    <input type="submit" name="Submit" class="btn btn-primary">
    {{ Form::close() }}
  </div>
</div>

<div class="card mb-3">
  <div class="card-header">Post new status</div>

  <div class="card-body">
    <form action="{{ route('status.store') }}" method="POST">
      {{ csrf_field() }}
      <div class="form-group">
        <textarea name="status-content" id="new-status-textarea" rows="3" class="form-control"
                  placeholder="What's on your mind"></textarea>
      </div>

      <input type="submit" name="Submit" class="btn btn-primary">
    </form>
  </div>
</div>

resources/views/partials/post-card.blade.php
@if ($post->type_id === \App\Models\PostType::STATUS)
  <div class="post-wrapper">
    <div class="card">
      <div class="card-body pb-2">
        <div class="d-flex mb-2">
          <div style="max-width: 65px; max-height: 65px">
            <img src="{{ $post->user->profile_photo_thumbnail_path }}"
                 class="img-fluid rounded"
                 alt="{{ $post->user->name }}'s profile photo">
          </div>
          <div class="f-flex flex-column ml-2 mt-1">
            <h5 class="mb-1"><a href="{{ route('profile.show', $post->user) }}"
                                class="profile-name">{{ $post->user->name }}</a></h5>
            <small class="text-muted">{{ $post->created_at->diffForHumans() }}</small>
          </div>
        </div>
        <div class="status-content">
          {!! $post->status->content !!}
        </div>
      </div>
      @include('partials.post.actions')
      @include('partials.post.comment-section')
    </div>
  </div>
@elseif ($post->type_id === \App\Models\PostType::TIMELINE_PHOTO)
  <div class="post-wrapper">
    <div class="card">
      <div class="card-body pb-3">
        <div class="d-flex mb-2">
          <div style="max-width: 65px; max-height: 65px">
            <img src="{{ $post->user->profile_photo_thumbnail_path }}"
                 class="img-fluid rounded"
                 alt="{{ $post->user->name }}'s profile photo">
          </div>
          <div class="f-flex flex-column ml-2 mt-1">
            <h5 class="mb-1"><a href="{{ route('profile.show', $post->user) }}"
                                class="profile-name">{{ $post->user->name }}</a></h5>
            <small class="text-muted">{{ $post->created_at->diffForHumans() }}</small>
          </div>
        </div>

        <div class="status-content">
          {!! $post->timeline_photo->description !!}
        </div>

        <div class="pt-2">
          <img src="{{ $post->timeline_photo->medium_path }}" alt="" class="img-fluid">
        </div>
      </div>
      @include('partials.post.actions')
      @include('partials.post.comment-section')
    </div>
  </div>
@endif

resources/views/partials/user-card.blade.php
<div class="user-card-wrapper">
  <div class="card">
    <div class="inner-wrapper d-flex">
      <div class="w-25 p-1">
        <img src="{{ $user->profile_photo_thumbnail_path }}" alt="" class="img-fluid">
      </div>
      <div class="right p-2 d-flex flex-column justify-content-between flex-wrap">
        <h5><a class="profile-name" href="{{ route('profile.show', $user) }}">{{ $user->name }}</a></h5>
        @if ($friendship = Auth::user()->isFriendWith($user))
          <form action="{{ route('friendship.remove', $friendship) }}" method="POST">
            {{ csrf_field() }}
            <input type="submit" class="btn btn-outline-danger btn-sm" value="Remove friend">
          </form>
        @elseif ($friendship = Auth::user()->hasPendingFriendRequestWith($user))
          @if ($friendship->sender_id === Auth::user()->id)
            <button class="btn btn-outline-secondary btn-sm" disabled aria-disabled="true">Friend request sent</button>
          @else
            <div class="d-flex flex-row justify-content-start">
              <form action="{{ route('friendship.accept', $friendship) }}" method="POST">
                {{ csrf_field() }}
                <input type="submit" class="btn btn-outline-success btn-sm" value="Accept friend">
              </form>
              <form class="ml-2" action="{{ route('friendship.refuse', $friendship) }}" method="POST">
                {{ csrf_field() }}
                <input type="submit" class="btn btn-outline-dark btn-sm" value="Refuse friend">
              </form>
            </div>
          @endif
        @else
          <form action="{{ route('friendship.add', $user) }}" method="POST">
            {{ csrf_field() }}
            <input type="submit" class="btn btn-outline-primary btn-sm" value="Add friend">
          </form>
        @endif
      </div>
    </div>
  </div>
</div>